version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: simplelibrary-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simplelibrary
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:4
    container_name: simplelibrary-adminer
    depends_on:
      - mysql
    ports:
      - "8081:8080"

volumes:
  mysql_data:

